#########################################################################################
# This file describes three Confluent Platform environments, used for our demo scenario.
#
clusters:
  - name: cluster_0 # from, e.g., the Web UI
    type: DEV #DEV/QA/ROD

    # from cloud ui
    clusterId: lkc-d8w1o
    clusterType: basic
    provider: GCP
    region: us-east4
    availability: single zone

    # defined by organization
    owner: Mirko
    ownerContact: mirko@confluent.io
    org: Confluent Inc.
    tags:
      - low-performance
      - insecure
      - open
      - developer_sandbox

    principals:
      com.mybusiness.depA.prod: USER:1234
      com.mybusiness.depA.cons: USER:5678

    domainFileFolders:
      - ./src/main/cluster-state-tools-data/example2/domains/com.mybusiness

    clusterLevelAccessPath: ./src/main/cluster-state-tools-data/example2/cla.yaml

    # provided by cluster admin
    clientProperties:
      # technical details for accessing kafka-service
      kafka:
        bootstrap.servers: pkc-419q3.us-east4.gcp.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${CLUSTER_API_KEY}"  password="${CLUSTER_API_SECRET}";
        sasl.mechanism: PLAIN

      # technical details for accessing schema-registry-service
      schemaRegistry:
        schema.registry.url: https://psrc-4v1qj.eu-central-1.aws.confluent.cloud
        basic.auth.credentials.source: USER_INFO
        schema.registry.basic.auth.user.info: ${SR_API_KEY}:${SR_API_SECRET}

      # technical details to access the kubernetes stack
      knowledgeGraphService:
        type: Neo4J-service
        url: http://localhost:7474

  #
  # Here, we have only essential properties, no optional Kubernetes stack and no graph-db.
  #
  - name: cluster_1_QA # defined by organization
    type: QA
    clusterId: lkc-20kwy # from cloud ui
    clusterType: basic
    provider: AWS
    region: eu-north-1
    availability: single zone

    owner: Jim
    ownerContact: jim@mybusiness.com
    org: MyBusiness
    tags:
      - high-performance
      - secure
      - managed
    principals:
      ao.socketserver.principal.prod.env: USER:1234
      ao.socketserver.principal.cons.env: USER:5678

    domainFileFolders:
      - ./src/main/cluster-state-tools-data/example2/domains/com.mybusiness

    clusterLevelAccessPath: ./src/main/cluster-state-tools-data/example2/cla.yaml

    clientProperties:
      # technical details for accessing kafka-service
      kafka:
        bootstrap.servers: pkc-zm3p0.eu-north-1.aws.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule   required username="${CLUSTER_API_KEY}"   password="${CLUSTER_API_SECRET}";
        sasl.mechanism: PLAIN
      # technical details for accessing schema-registry-service
      schemaRegistry:
        schema.registry.url: https://psrc-lq3wm.eu-central-1.aws.confluent.cloud
        basic.auth.credentials.source: USER_INFO
        schema.registry.basic.auth.user.info: ${SR_API_KEY}:${SR_API_SECRET}

  #
  # Here, we have only essential properties, no optional Kubernetes stack and no graph-db.
  #
  - name: cluster_1_PROD
    type: PROD
    # from cloud ui
    clusterId: lkc-y35qj
    clusterType: basic
    provider: AZURE
    region: northeurope
    availability: single zone

    # defined by organization
    owner: Jim
    ownerContact: jim@mybusiness.com
    org: MyBusiness
    tags:
      - high-performance
      - secure
      - managed
    principals:
      com.mybusiness.depA.prod: USER:1234
      com.mybusiness.depA.cons: USER:5678

    domainFileFolders:
      - ./src/main/cluster-state-tools-data/example2/domains/com.mybusiness

    clusterLevelAccessPath: ./src/main/cluster-state-tools-data/example2/cla.yaml

    clientProperties:
      kafka:
        # technical details for accessing kafka-service
        bootstrap.servers: pkc-lz6r3.northeurope.azure.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule   required username="${CLUSTER_API_KEY}"   password="${CLUSTER_API_SECRET}";
        sasl.mechanism: PLAIN
      # technical details for accessing schema-registry-service
      schemaRegistry:
        schema.registry.url: https://psrc-lg26v.westeurope.azure.confluent.cloud
        basic.auth.credentials.source: USER_INFO
        schema.registry.basic.auth.user.info: ${SR_API_KEY}:${SR_API_SECRET}
