#########################################################################################
# This file describes three Confluent Platform environments, used for our demo scenario.
#
clusters:
  - name: cluster_ABC # from, e.g., the Web UI
    type: DEV #DEV/QA/ROD

    # from cloud ui
    clusterId: lkc-jwgvw
    clusterType: basic
    provider: GCP
    region: us-east1
    availability: single zone

    # defined by organization
    owner: Mirko
    ownerContact: mirko@confluent.io
    org: Confluent Inc.
    tags:
      - low-performance
      - insecure
      - open
      - developer_sandbox

    principals:
      com.mybusiness.depA.prod: USER:1234
      com.mybusiness.depA.cons: USER:5678

### TURN THIS INTO A list of domain folders
    domainFileFolder: ./src/main/cluster-state-tools-data/example2/domains
### TURN THIS INTO A files
    clusterLevelAccessFolder: ./src/main/cluster-state-tools-data/example2/cla

    # provided by cluster admin
    clientProperties:
      # technical details for accessing kafka-service
      kafka:
        bootstrap.servers: pkc-4yyd6.us-east1.gcp.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${CLUSTER_API_KEY}"  password="{CLUSTER_API_SECRET}";
        sasl.mechanism: PLAIN

      # technical details for accessing schema-registry-service
      schemaRegistry:
        schema.registry.url: https://psrc-4v1qj.eu-central-1.aws.confluent.cloud
        basic.auth.credentials.source: USER_INFO
        schema.registry.basic.auth.user.info: ${SR_API_KEY}:${SR_API_SECRET}

      # technical details to access the kubernetes stack
      knowledgeGraphService:
        type: Neo4J-service
        url: http://localhost:7474

  #
  # Here, we have only essential properties, no optional Kubernetes stack and no graph-db.
  #
  - name: cluster_CDE # defined by organization
    type: QA
    clusterId: lkc-jwxyz # from cloud ui
    clusterType: basic
    provider: GCP
    region: us-east1
    availability: single zone

    owner: Jim
    ownerContact: jim@mybusiness.com
    org: MyBusiness
    tags:
      - high-performance
      - secure
      - managed
    principals:
      ao.socketserver.principal.prod.env: USER:1234
      ao.socketserver.principal.cons.env: USER:5678

    #domainFileFolder: ./src/main/cluster-state-tools-data/example2/domains

    clusterLevelAccessFolder: ./src/main/cluster-state-tools-data/example2/cla

    clientProperties:
      # technical details for accessing kafka-service
      kafka:
        bootstrap.servers: pkc-4yyd6.us-east1.gcp.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule   required username="${CLUSTER_API_KEY}"   password="${CLUSTER_API_SECRET}";
        sasl.mechanism: PLAIN
      # technical details for accessing schema-registry-service
      schemaRegistry:
        schema.registry.url: https://psrc-4v1qj.eu-central-1.aws.confluent.cloud
        basic.auth.credentials.source: USER_INFO
        schema.registry.basic.auth.user.info: ${SR_API_KEY}:${SR_API_SECRET}

  #
  # Here, we have only essential properties, no optional Kubernetes stack and no graph-db.
  #
  - name: PROD-cluster-101
    type: PROD
    # from cloud ui
    clusterId: lkc-jwxyz
    clusterType: basic
    provider: GCP
    region: us-east1
    availability: single zone

    # defined by organization
    owner: Jim
    ownerContact: jim@mybusiness.com
    org: MyBusiness
    tags:
      - high-performance
      - secure
      - managed
    principals:
      ao.socketserver.principal.prod.env: USER:1234
      ao.socketserver.principal.cons.env: USER:5678

    #domainFileFolder: ./src/main/cluster-state-tools-data/example2/domains

    clusterLevelAccessFolder: ./src/main/cluster-state-tools-data/example2/cla

    clientProperties:
      kafka:
        # technical details for accessing kafka-service
        bootstrap.servers: pkc-4yyd6.us-east1.gcp.confluent.cloud:9092
        security.protocol: SASL_SSL
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule   required username="${CLUSTER_API_KEY}"   password="${CLUSTER_API_SECRET}";
        sasl.mechanism: PLAIN
      # technical details for accessing schema-registry-service
      schemaRegistry:
        schema.registry.url: https://psrc-4v1qj.eu-central-1.aws.confluent.cloud
        basic.auth.credentials.source: USER_INFO
        schema.registry.basic.auth.user.info: ${SR_API_KEY}:${SR_API_SECRET}
